pekko {

  loglevel = "DEBUG"

  actor {
    provider = cluster

    serialization-bindings {
      "cluster.CborSerializable" = jackson-cbor
    }
  }

  remote.artery {
    transport = tcp
    canonical.hostname = "127.0.0.1"
    canonical.port = ${clustering.port}
  }

  cluster {

    seed-nodes = [
      "pekko://ClusterSystem@127.0.0.1:25251",
      "pekko://ClusterSystem@127.0.0.1:25252"
    ]

    downing-provider-class =
      "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    sharding {

      passivation {

        default-idle-strategy {

          idle-entity.timeout = 2 minutes

        }
      }
    }
  }
}

clustering {

  port = 25251

}

